image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data:
distortion_model: plumb_bob
distortion_coefficients:
  rows: 5
  cols: 1
  data:
rectification_matrix:
  rows: 3
  cols: 3
  data:
projection_matrix:
  rows: 3
  cols: 4
  data:
